runtime: nodejs
env: flex
env_variables:
  SQL_USER: root
  SQL_PASSWORD: "Mahe@@88"
  SQL_DATABASE: homeassignment
  INSTANCE_CONNECTION_NAME: home-assignment-api:asia-southeast1:home-assignment-api
beta_settings:
  cloud_sql_instances: home-assignment-api:asia-southeast1:home-assignment-api